name: Kubernetes Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up gcloud CLI
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '426.0.0' # Specify the gcloud version you want to use
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Step 3: Authenticate kubectl with GKE
    - name: Authenticate with GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Detect Changed Files and Apply
    - name: Deploy only changed YAML files
      run: |
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep k8s/)
        else
          # Handle first commit case
          CHANGED_FILES=$(git ls-files k8s/)
        fi

        # Apply changed YAML files
        for file in $CHANGED_FILES; do
          echo "Applying $file..."
          kubectl apply -f $file
        done
